:timeout: 25
:concurrency: 5
production:
  :concurrency: 10
:queues:
  - ["critical", 240] # Used for audit logging and routing. Should be emptied as soon as possible, before anything else runs.
  - ["default", 24] # Application jobs should run more often.
  - ["webhook", 12] # Used to enqueue integrations without api calls.
  - ["netout", 4] # API calls to 3rd parties not directly related to webhook processing, like webhook subscriptions and backfills.
